version: '3.7'

services:
  couchdb:
    container_name: couchdb
    hostname: couchdb.local
    image: 'apache/couchdb:${DOCKER_TAG:-latest}'
    environment:
      - 'COUCHDB_USER=admin'
      - 'COUCHDB_PASSWORD=admin'
    volumes:
      - '~/data:/opt/couchdb/data'
    ports:
      - '5984:5984'
